### ISSUE TITLE
Would be great to have example or how-to add new Serializable objects 

### ISSUE THREAD

**Issue by sergio-bershadsky** [irmen/Pyro5#14]
From my pov, it's not a big deal to add a new custom object to be serialized/deserialized by Serpent. But it will be helpful.

**Comment by irmen** [comment]
https://github.com/irmen/Pyro5/tree/master/examples/ser_custom  ?

**Comment by irmen** [comment]
@sergio-bershadsky is the example I linked above not what you are looking for?

**Comment by sergio-bershadsky** [comment]
Sorry for a long delay, yes this example works for me and I have already implemented custom object transfer in my project. It would be more obvious if the example will be called `custom_serialization` or `user_object_transfer` it just lost in a big list of examples when I tried to find it. Also, internal API is not simple and it was challenging to make it work as expected. I see that you are in a step of a big refactoring. I will be glad to join you and support your project as possible as I can! Thanks!
