### ISSUE TITLE
Is bytes type supported?

### ISSUE THREAD

**Issue by zbynekdrlik** [irmen/Pyro5#26]
Bytes is basic python type but when I call pyro object with bytes parameter on server side it si dict. How to get correct deserialization atomaticaly?

**Comment by irmen** [comment]
Byte type is supported but with a documented caveat when using the default serpent serializer: https://pyro5.readthedocs.io/en/latest/tipstricks.html#binary-data-transfer-file-transfer 

The documentation there explains why that is and what you can use as an alternative.
For instance, using the marshal serializer or perhaps using the message annotations.
