### ISSUE TITLE
Question about mysterious delays

### ISSUE THREAD

**Issue by tbhkuiper** [irmen/Pyro5#30]
This is a question for the community.  I have implemented a client/server pair with callback in the manner suggested by Irmen. (Client is itself a server for the callbacks.)  The server is experiencing occasional delays of a few tenths of seconds.  The server has five threads, four in parallel and one collecting the results to be returned via the callback.  All threads experience these delays, so that ms calculations take a few tenths of a second, roughly one time in ten.  Could Pyro5 be causing this?  Thanks.

**Comment by tbhkuiper** [comment]
On 9/4/20 3:34 PM, Irmen de Jong wrote:
> Could it be that you're just seeing effects of Python's GIL?

Thank you for that.  I will investigate.

**Comment by tbhkuiper** [comment]
Yes, you were right.  In a `while` loop waiting for a time to elapse I had `pass` instead of `time.sleep(0.001).`  Thank you.

**Comment by tbhkuiper** [comment]
Incidentally, I had an audible clue I was ignoring -- the CPU fan coming on!

**Comment by irmen** [comment]
closing this as I believe the issue was resolved. If not feel free to re-open
