### ISSUE TITLE
Suppress Serialization/ reflexive method call

### ISSUE THREAD

**Issue by gkaissis** [irmen/Pyro5#40]
Is it possible to use the SerializedBlob (or some other construct) to suppress serialization on a certain return statement? We would like to send a plain bytestring which is efficiently pre-serialized in a custom format directly via return from an RPC to a daemon.

also: is there a simple way to perform a reflexive rpc call? Example:

```py
#(Proxy side)
def do_something_onproxy():
    ...
    return b'proxy says hello'

server_msg=server.do_something()
print(server_msg)

>>server says hello

#(Server side)
def do_something_onserver():
    ...
    proxy_msg=proxy.do_something()
    return b'server says hello'
    
print(proxy_msg)
>>proxy says hello
```

I looked into the callback example but it left me a tad confused...

Thanks and congratulations for your great work on this project!

**Comment by irmen** [comment]
SerializedBlob is only for request arguments and is meant to avoid double serialization of complex data that is already serialized.

If it's just raw bytes you're transferring, try one of the other methods: https://pyro5.readthedocs.io/en/latest/tipstricks.html#binary-data-transfer-file-transfer

Second question: what do you mean exactly with "reflexive rpc call"?

**Comment by gkaissis** [comment]
Thanks a lot for the clarification!

By reflexive, I mean a client call to the server which triggers a server call to the client. I suppose "callback" is the closest to what I am thinking, but the mental model of the "server" calling the "client" isn't entirely clear to me from the example. My concrete use-case is the following:
- The client triggers a long-running computation on the server
- As soon as the server is done it calls a function on the client to signal it's ready
-  This triggers a client function to fetch the result from the server
-  The client processes the fetched result and processes it
- Lastly, the client triggers another function on the server to fetch the result from the client again

I hope this makes sense...
Thanks again!

**Comment by irmen** [comment]
@gkaissis you closed the issue, managed to get the callbacks working?

**Comment by gkaissis** [comment]
I did, but then refactored the routine to be more Pyro-like with remote generators and a one-way call which made it both faster and more elegant. Thanks for your help!

**Comment by irmen** [comment]
I am glad you found a good solution !
