### ISSUE TITLE
Proxy from sshtunnel

### ISSUE THREAD

**Issue by coreegor** [irmen/Pyro5#42]
Is it possible to connect to server via jump host by sshtunnel?

**Comment by irmen** [comment]
Yeah that should be possible, if you're having issues check https://pyro5.readthedocs.io/en/latest/tipstricks.html#pyro-behind-a-nat-router-firewall  some of that may be relevant for this too

**Comment by gkaissis** [comment]
It works fine with sshtunnel in my experiments. Just assign the daemon to the loopback address and port on the server system, do the same with the proxy on the client system and then bind local to remote via ssh. The performance penalty is pretty drastic though (about 10x slower vs. regular TCP sockets in my experiments)

**Comment by irmen** [comment]
Also, don't forget that Pyro5 supports SSL by itself as well.  (this doesn't help with tunneling, but does give you encryption and authentication:  https://pyro5.readthedocs.io/en/latest/security.html?highlight=ssl#secure-communication-via-ssl-tls

**Comment by coreegor** [comment]
Great, Thx.
