### ISSUE TITLE
Proxy does not expose some special methods correctly

### ISSUE THREAD

**Issue by eudoxos** [irmen/Pyro5#44]
Some special methods, such as `__len__` or `__getitem__` do not go through `__getattr__` when called via their special syntax: `len(a)` will not look for `__len__` using `__getattr__` (but `a.__len__` will use `__getattr__`), just like `a[0]` (vs. `a.__getitem__`) .

Python documentation on [Special method lookup](https://docs.python.org/3/reference/datamodel.html?highlight=data%20model#special-method-lookup) says in the last paragraph:

> Bypassing the `__getattribute__()` machinery in this fashion provides significant scope for speed optimisations within the interpreter, at the cost of some flexibility in the handling of special methods (the special method must be set on the class object itself in order to be consistently invoked by the interpreter).

[Pyro5 documentation](https://pyro5.readthedocs.io/en/latest/servercode.html#creating-a-pyro-class-and-exposing-its-methods-and-properties) says:

> You *can* expose a ‘dunder’ method with double underscore for example `__len__`. 

which however does not work as expected — the special syntax such as `len(a)` will not work.

The solution would be to define those few special methods on the `Proxy` class itself, and have them raise an exception if they are not really exposed by the proxy. 

A case in the point is [here](https://github.com/mupif/mupif/blob/a0a3e86e96ff5188bf12ec1b3182d632af940908/mupif/tests/test_heavydata.py#L120) which uses the workaround of explicit `__getitem__`:

```python
self.assertEqual(root.__getitem__(0).getMolecules().__getitem__(0).getAtoms().__getitem__(0).getIdentity().getElement(),'Q')
```

**Comment by irmen** [comment]
Regarding iteration over a proxy, note that it is possible already to return an _iterator_ object from a pyro method.
https://pyro5.readthedocs.io/en/latest/clientcode.html?highlight=streaming#remote-iterators-generators

**Comment by irmen** [comment]
The __iter__ handling doesn't work, and can be omitted actually. Python does the right thing when requesting an itertation over the  proxy object already.
