### ISSUE TITLE
httpgateway

### ISSUE THREAD

**Issue by phil2nice** [irmen/Pyro5#54]
I suggest some modifications on pyro5 httpgateway in order to handle CORS Browsers Security Policy
Http Method "OPTIONS" should be handled with following includings in  response header

('Access-Control-Allow-Origin', pyro_app.cors),
('Access-Control-Allow-Methods', 'GET, POST, OPTIONS'),
('Access-Control-Allow-Headers', 'Content-Type')

pyro_app.cors will contain a parameter we could provide on a new launcher -C option.
could be * to authorize every domain ou your specific Domain/URL

Once done, it's easy to have a Vuejs App calling to gateway to interact with pyro services proxies.

**Comment by irmen** [comment]
closing this as it was merged. Thanks for the contribution.
