### ISSUE TITLE
Switching between multiple server doesn't work

### ISSUE THREAD

**Issue by ZhendongTian** [irmen/Pyro5#60]
When I create a new Pyro5.api.Proxy on my client it corrupt the existing connection.

**Comment by irmen** [comment]
Please be a bit more descriptive. What error do you see? And give some example code that triggers the issue.
Otherwise we can't help

**Comment by ZhendongTian** [comment]
> Please be a bit more descriptive. What error do you see? And give some example code that triggers the issue.
> Otherwise we can't help

WHat I did before was starting multiple server of the same class then use the handler in the same client/thread. I have discovered that this will lead to a crush and it seems object gets reinitialized if you switch object. 

The solution is to name the class a different name on a different server.

**Comment by irmen** [comment]
Yeah- you can't use duplicate identical names on different servers, no. That will utterly confuse the name lookup-- what server object should it return?

**Comment by ZhendongTian** [comment]
> Yeah- you can't use duplicate identical names on different servers, no. That will utterly confuse the name lookup-- what server object should it return?

I’m not very familiar with how Pyro is implemented on low level, but assuming the server object it’s being wrapped by some other class, shouldn’t this be ok to have multiple remote object? after all creating multiple object of the same class and reference them with different name locally is ok. But If I’m to make something similar to pyro I will just wrap them with some Async method and calling the function becomes calling coroutines, so I was wondering why didn’t pyro take this approach?

**Comment by irmen** [comment]
I am still unsure exactly how your setup is, but with Pyro you are usually registering _classes_ rather than objects.
Then, you are able to control the instancing strategy with ``@behavior`` decorator, [see here](https://pyro5.readthedocs.io/en/latest/servercode.html?highlight=instance#controlling-instance-modes-and-instance-creation).
This allows you to serve a single singleton object, or many different instances if you wish.

**Comment by irmen** [comment]
I trust that the solution to your issue for accessing multiple objects of the same class lies in choosing the correct instancing strategy that you can configure with the behavior decorator, mentioned above.
So I'm closing this issue.
If this is not correct, please reopen but provide a piece of example code that reproduces the precise issue you're having.
