### ISSUE TITLE
Reconnect to proxy doesn't connect to running object.

### ISSUE THREAD

**Issue by ZhendongTian** [irmen/Pyro5#62]
This happens when I restart my python kernel, if I try to reconnect to the proxy by using Pyro5.api.Proxy('Pyro....') while passing the existing server uri, it seems to be starting a new object instead of using the old object.
Is there any way to connect to the existing object instead?

**Comment by irmen** [comment]
Yes, as pointed out in the other issue too; there is the ``@behavior`` decorator
https://pyro5.readthedocs.io/en/latest/servercode.html?highlight=instance#controlling-instance-modes-and-instance-creation

The default instance creation mode is to create a new server side object per proxy connection.
If you want the same object instance for every connection, use instance_mode="single"
