### ISSUE TITLE
Use generic for expose?

### ISSUE THREAD

**Issue by nelsyeung** [irmen/Pyro5#63]
Is it possible to use [Generic](https://docs.python.org/3/library/typing.html#typing.Generic) for the `expose` decorator? Currently, we can't get the right type hints for exposed methods.

For example:

```python
class Warehouse:
    @expose
    def store(self, name: str, item: str) -> None:
        print("{0} stored the {1}.".format(name, item))

    ...

class Person:
    def deposit(self, warehouse: Warehouse):
        item = input("Type a thing you want to store (or empty): ").strip()
        if item:
            warehouse.store(self.name, item)

    ...
```

The `warehouse.store(self.name, item)` will give the type hint `(method) store: ((...) -> Unknown) | type`, which is basically useless, as I can pass in `item` as `int` and it won't complain.

**Comment by irmen** [comment]
What do you propose? From what I read, Generic is an abstract base class and is meant to "create generic types". I don't see how this is applicable to expose().

**Comment by nelsyeung** [comment]
Ah, sorry for the misunderstanding. I kind of just used the general term generics for generic types and generic functions. 

What I meant was something like this:

```python
from collections.abc import Callable
from typing import TypeVar

_T = TypeVar("_T", bound=Union[Callable, type])

def expose(method_or_class: _T) -> _T:
    ...
```

Here's a full minimal example, where you can see the correct type hints in action (I'm using Pyright in Vim):

```python
from collections.abc import Callable
from typing import TypeVar, Union

_T = TypeVar("_T", bound=Union[Callable, type])

def expose(method_or_class: _T) -> _T:
    print("foo")
    return method_or_class

@expose
class Foo:
    def foo(self) -> None:
        print("foo")

class Bar:
    @expose
    def bar(self, bar: str) -> str:
        print(bar)
        return bar


Foo().foo()  # <- Hover your cursor over foo()
Bar().bar("a")  # <- Hover your cursor over bar()
```

**Comment by irmen** [comment]
I'm not familiar enough with TypeVar or the effect of `_T = TypeVar("_T", bound=Union[Callable, type])` 
but the change seems harmless.
