### ISSUE TITLE
httpgateway should not involve Pyro code with OPTION method (CORS) to avoid double calls

### ISSUE THREAD

**Issue by phil2nice** [irmen/Pyro5#66]
Hello
In the httpgateway.py code I delivered some times in the past, I noticed that all the pyro code is involved even with the OPTION method used for CORS. This leads to overhead the same code is then called twice. 
PYRO code should not be involved with OPTION method.
I have a new version of hittpgateway.py that corrects this point.

**Comment by irmen** [comment]
sure, stick it in a pull request like the previous time so I can have a look!
