### ISSUE TITLE
Autoproxy by class

### ISSUE THREAD

**Issue by Evidlo** [irmen/Pyro5#7]
I'm trying to use [PyKeePass](http://github.com/pschmitt/pykeepass) remotely to keep a password database open in a background process for a few minutes.  

Here are my server and client:

```python
import Pyro5.api
from pykeepass import PyKeePass as PyKeePassRemote

PyKeePass = Pyro5.api.expose(PyKeePassRemote)

@Pyro5.api.expose
class Factory(object):
    def PyKeePass(self, filename, password=None, keyfile=None):
        kp = PyKeePass(filename, password=password, keyfile=keyfile)
        self._pyroDaemon.register(kp)
        return kp

daemon = Pyro5.api.Daemon.serveSimple(
    {
        Factory: 'Factory'
    },
    host='localhost',
    port=9999,
    ns=False,
)

```
```python
import Pyro5.api
from lxml import etree

Factory = Pyro5.api.Proxy('PYRO:Factory@localhost:9999')

kp = Factory.PyKeePass('test3.kdbx', 'password', 'test3.key')
kp.entries
```
Under the hood, `kp.entries` builds a list of [Entry](https://github.com/pschmitt/pykeepass/blob/master/pykeepass/entry.py), [Group](https://github.com/pschmitt/pykeepass/blob/master/pykeepass/group.py), or [Attachment](https://github.com/pschmitt/pykeepass/blob/master/pykeepass/attachment.py) objects.

However, I get `TypeError: don't know how to serialize class <class 'lxml.etree._Element'>` because Pyro tries to serialize these objects which contain some lxml `_Element` and `_ElementTree` objects.

In general, is there a way to tell Pyro5 to automatically pass objects of a certain type as remote objects rather than building adapters around every function in PyKeePass?

**Comment by irmen** [comment]
No, not in a general sense.
Pyro only exposes objects via autoproxying if these objects are Pyro objects. So you'll have to do a little manual work (registering them with the daemon) before returning them. See the 'autoproxy' example and the documentation of this feature.
Main reason is security and the principle to keep the remotely exposed interface explicit.
