### ISSUE TITLE
Docs request: linking threadproxysharing

### ISSUE THREAD

**Issue by jamesbraza** [irmen/Pyro5#74]
From https://pyro5.readthedocs.io/en/latest/clientcode.html?highlight=threadproxysharing#proxy-sharing-between-threads:

> See the `threadproxysharing` example for more details.

I realized to see this snippet, we have to:
1. Open the GitHub repo
2. Navigate to [`examples/threadproxysharing/client.py`](https://github.com/irmen/Pyro5/blob/master/examples/threadproxysharing/client.py)

Would you be willing to hyperlink this example file in the docs, for reader's convenience?  🤓

**Comment by irmen** [comment]
Could be convenient.
There are many more references to examples so these have to be updated as well though, to be complete.

**Comment by jamesbraza** [comment]
Nice work!
