### ISSUE TITLE
Pyro takes 5 seconds to run the example `greeting_client.py` script

### ISSUE THREAD

**Issue by bmitc** [irmen/Pyro5#89]
I am using Python 3.12.1 on both Windows 11 with Pyro5 5.15, and I started out my testing of Pyro5 with the example show here: https://pyro5.readthedocs.io/en/latest/intro.html#simple-example

* File `greeting_server.py`:
    ```python
    import Pyro5.api
    
    
    @Pyro5.api.expose
    class GreetingMaker(object):
        def get_fortune(self, name):
            return (
                "Hello, {0}. Here is your fortune message:\n"
                "Tomorrow's lucky number is 12345678.".format(name)
            )
    
    
    daemon = Pyro5.server.Daemon()  # make a Pyro daemon
    ns = Pyro5.api.locate_ns()  # find the name server
    uri = daemon.register(GreetingMaker)  # register the greeting maker as a Pyro object
    ns.register(
        "example.greeting", uri
    )  # register the object with a name in the name server
    
    print("Ready.")
    daemon.requestLoop()  # start the event loop of the server to wait for calls

* File `greeting_client.py`:

```python
    import time
    import Pyro5.api
    
    name = input("What is your name? ").strip()
    
    greeting_maker = Pyro5.api.Proxy(
        "PYRONAME:example.greeting"
    )  # use name server object lookup uri shortcut
    
    start_time = time.time()
    
    print(greeting_maker.get_fortune(name))
    
    print("Execution time: " + str(time.time() - start_time))
```

* Then I run the following commands in three separate terminals:

```
poetry run python -m Pyro5.nameserver
poetry run python .\pyro_test\greeting_server.py
poetry run python .\pyro_test\greeting_client.py
```

This takes around 5 seconds my relatively powerful machine to run `greeting_maker.get_fortune(name)`. What is going on here? I am investigating Pyro5 to build a distributed system with some fault tolerance, all of the Pyro5 servers would run on the same machine. I am attempting to have a system that would have Erlang/Elixir type of properties but in Python. But this performance has me concerned.

**Comment by irmen** [comment]
Investigate where the time is spent. Sounds to me like a DNS lookup issue that blocks the program.

**Comment by irmen** [comment]
"inside Pyro" is extremely vague.  Most of what pyro does is calling the OS's network socket functions, for example.

I suspect the locate_ns() call is not finding the name server directly so it reverts to a slower broadcast solution. There are various options to work around this, if you don't want to fix the system's DNS. These are all mentioned in the Pyro documentation.  Start here for example https://pyro5.readthedocs.io/en/latest/nameserver.html#configuration-items

**Comment by irmen** [comment]
Alternatively, you could try another one of the examples such as the "benchmark" one. It doesn't use a name server , so it may tell you if the delay is indeed related to the NS lookup. 
https://github.com/irmen/Pyro5/tree/master/examples/benchmark

**Comment by irmen** [comment]
Pyro itself can also write a trace log file if you set the correct configuration options. 

But it seems Windows does something funky related to "localhost" ip resolution.  Easiest probably is to not let the name server (and maybe even the other Pyro servers) bind on "localhost" but instead supply the actual host name of the machine to bind on.
